language: python
sudo: false
cache: pip

python:
  - "3.6"

env:
  - DJANGO="django>=1.11,<2.2"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - flake8
  - ./runisort

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=template_library runtests.py
  - ./runcheckmigration
  - ./tests/manage.py makemigrations --dry-run | grep "No changes detected"
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      checkcommit --message "$COMMIT_MESSAGE"
    fi

after_success:
  coveralls
